language: python
python:
  - "3.8"
sudo: required
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - PYTHONPATH=. py.test --verbose -s --cov=.
deploy:
  on:
    branches: master
  provider: heroku
  app: lucyna
  api_key: ${HEROKU_API_KEY} 
